# Generated by Django 5.2.8 on 2025-11-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estorewebApp', '0003_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
