# Generated by Django 6.0.5 on 2026-05-12 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estorewebApp', '0012_wishlist_wishlistitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('rate_limit', 'Rate Limit'), ('login_failed', 'Login Failed'), ('login_locked', 'Login Locked'), ('coupon_invalid', 'Coupon Invalid')], max_length=30)),
                ('username', models.CharField(blank=True, default='', max_length=150)),
                ('ip_address', models.CharField(blank=True, default='', max_length=64)),
                ('path', models.CharField(blank=True, default='', max_length=255)),
                ('details', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
