# Generated by Django 6.0.5 on 2026-05-13 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estorewebApp', '0013_securityauditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Homepage Banner', max_length=120)),
                ('image', models.ImageField(upload_to='hero_banners/')),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
    ]
